import{S as m,i as l}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d=o=>o.map(({webformatURL:s,largeImageURL:r,tags:i,likes:e,comments:t,views:a,downloads:u})=>`
          <li class="gallery-item">
            <a href="${r}" class="gallery-link">
              <img src="${s}" alt="${i}" class="gallery-img">
            </a>
            <div class="small-content">
              <small class="text-likes">Likes: ${e}</small>
              <small class="text-views">Views: ${a}</small>
              <small class="text-comments">Comments: ${t}</small>
              <small class="text-downloads">Downloads: ${u}</small>
            </div>
          </li>`).join("");new m(".gallery a",{captionsData:"alt",captionDelay:250});const f="43933435-35fbbd09623d667ed19d4c9fb",p="https://pixabay.com/api/";async function h(o){const s=new URLSearchParams({key:f,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=await axios.get(`${p}?${s}`);if(r.status!==200)throw new Error(r.statusText);return r.data}const n=document.querySelector(".gallery-list"),y=document.querySelector(".search-form"),c=document.querySelector(".js-loader");function g(o){o.preventDefault();const s=o.target.elements.keyboardSearch.value.trim();if(s===""){n.innerHTML="",o.target.reset(),l.error({title:"Error",message:"Search query cannot be empty!",position:"topRight",timeout:2e3});return}n.innerHTML="",c.classList.remove("is-hidden"),h(s).then(r=>{if(r.totalHits===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"red"}),c.classList.add("is-hidden");return}n.innerHTML=d(r.hits),new m(".gallery a",{captionsData:"alt",captionDelay:250})}).catch(r=>{l.error({title:"Error",message:"Something went wrong, please try again later!",position:"topRight",timeout:2e3})}).finally(()=>{o.target.reset(),c.classList.add("is-hidden")})}y.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
